/// Flutter icons ReciepIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ReciepIcons
///      fonts:
///       - asset: fonts/ReciepIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ReciepIcons {
  ReciepIcons._();

  static const _kFontFam = 'ReciepIcons';
  static const String? _kFontPkg = null;

  static const IconData indicator = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData ph_code = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flame = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData goal = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData ph_sun_dim = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData cil_fridge = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
